<html>

<head></head>

<h2>Segnalazione errori</h2>
<p>Aggiornamento: ${.now}</p>
<p>Sistema: ${system}</p>
<table border="1" style="border-collapse: collapse; width: 100%; height: 36px;">
    <tbody>
    <tr style="height: 18px;">
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Created</strong></pre>
        </td>
        <td style="text-align: center;">
            <pre><strong>Bpmn Process Id</strong></pre>
        </td>
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Error Message</strong></pre>
        </td>
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Workflow Key</strong></pre>
        </td>
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Workflow Instance Key</strong></pre>
        </td>
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Job Key</strong></pre>
        </td>
        <td style="width: 14.2857%; height: 18px; text-align: center;">
            <pre><strong>Element Instance Key</strong></pre>
        </td>
    </tr>
    <tr style="height: 18px;">
        <td style="width: 14.2857%; height: 18px; text-align: left;">${Created}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${BpmnProcessId}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${ErrorMessage}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${WorkflowKey}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${WorkflowInstanceKey}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${JobKey}</td>
        <td style="width: 14.2857%; height: 18px; text-align: left;">${ElementInstanceKey}</td>
    </tr>
    </tbody>
</table>
</html>